export { default as withMerge} from './withMerge'
export { default as withSlots} from './withSlots'
export { default as withAppend} from './withAppend'
export { default as withApolloClient} from './withApolloClient'
export { default as withLocalStorage} from './withLocalStorage'
export { default as withContext} from './withContext'
export { default as withActiveState} from './withActiveState'
